<?php require_once("inc/init.php"); ?>

<button type="button" class="well" onclick="ouvertureAjout_projet();"><i class="fa fa-plus-square"></i>&nbsp;&nbsp;Nouvelle
    maintenance
</button>

<!-- modal-->
<div class="modal fade" id="modal_ajoute_maintenance" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        </div>
    </div>
</div> <!-- fin modal-->

<!-- row -->
<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-3" data-widget-editbutton="false"
             data-widget-fullscreenbutton="false">

            <header>
                <span class="widget-icon"> <i class="fa fa-users"></i> </span>
                <h2>Liste des maintenances</h2>
            </header>
            <!-- widget div-->
            <div>
                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->
                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body no-padding">
                    <form id="tableau">
                        <table id="listing_maintenance" class="table table-striped table-bordered table-hover"
                               width="100%">
                            <thead>
                            <tr>
                                <th>Type</th>
                                <th>Société</th>
                                <th>Application</th>
                                <th>Utilisateur</th>
                                <th>Date</th>
                                <th>Durée</th>
                                <th></th>
                            </tr>
                            </thead>
                        </table>
                    </form>

                </div>
                <!-- end widget content -->
            </div>
            <!-- end widget div -->
        </div>
        <!-- end widget -->
    </article>
    <!-- WIDGET END -->
</div>
<!-- end row -->

<script type="text/javascript">
    $(document).ready(function () {


        pageSetUp();

        var pagefunction = function () {

            localStorage.clear();

            var responsiveHelper_listing_maintenance = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };


            $('#listing_maintenance').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                "t" +
                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "oTableTools": {
                    "aButtons": [
                        "xls",
                        {
                            "sExtends": "pdf",
                            "sTitle": "Liste_clients_PDF",
                            "sPdfMessage": "Iwit Systems PDF Export",
                            "sPdfSize": "letter"
                        },
                        {
                            "sExtends": "print",
                            "sMessage": "Generated by Iwit Systems <i>(press Esc to close)</i>"
                        }
                    ],
                    "sSwfPath": "assets/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                },
                "autoWidth": true,
                "preDrawCallback": function () {
                    if (!responsiveHelper_listing_maintenance) {
                        responsiveHelper_listing_maintenance = new ResponsiveDatatablesHelper($('#listing_maintenance'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_listing_maintenance.createExpandIcon(nRow);
                },
                "ajax": "modules/maintenances/ajax/iListe_maintenance.php",
                "drawCallback": function (oSettings) {
                    responsiveHelper_listing_maintenance.respond();
                },
                "language": {
                    "url": "./data/French.json"
                }
            });
        };

        loadScript("assets/js/plugin/datatables/jquery.dataTables.min.js", function () {
            loadScript("assets/js/plugin/datatables/dataTables.colVis.min.js", function () {
                loadScript("assets/js/plugin/datatables/dataTables.tableTools.min.js", function () {
                    loadScript("assets/js/plugin/datatables/dataTables.bootstrap.min.js", function () {
                        loadScript("assets/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                    });
                });
            });
        });

    });
    function ouvertureAjout_projet() {
        $.ajax({
            url: 'modules/maintenances/modals/modal_ajout_maintenance.php',
            type: 'POST',
            data: '',
            dataType: 'html',
            success: function (contenu) {
                $('#modal_ajoute_maintenance .modal-content').html(contenu);
                $('#modal_ajoute_maintenance').modal('show');
            },
            error: function () {
                alert('erreur lors du retour JSON !');
            }
        });
    }

    function ouvertureModification_maintenance(paramId) {
        $.ajax({
            url: 'modules/maintenances/modals/modal_modification_maintenance.php',
            type: 'POST',
            data: {'id': paramId},
            dataType: 'html',
            success: function (contenu) {
                $('#modal_ajoute_maintenance .modal-content').html(contenu);
                $('#modal_ajoute_maintenance').modal('show');
            },
            error: function () {
                alert('erreur lors du retour JSON !');
            }
        });
    }

    function ouvertureModification_projet(paramId) {
        window.location = './#ajax/modification_projet.php?id=' + paramId;
    }

    function suppressionLigne(paramId) {
        $.SmartMessageBox({
            title: "Attention !",
            content: "Vous êtes sur le point de supprimer cete maintenance, confirmer ?",
            buttons: '[Non][Oui]'
        }, function (ButtonPressed) {
            console.log(paramId);
            if (ButtonPressed === "Oui") {
                $.ajax({
                    url: 'modules/maintenances/modals/modal_suppression_maintenance.php',
                    type: 'POST',
                    data: {'id': paramId},
                    dataType: 'html',
                    success: function (contenu) {
                        smallBox('Suppression', "Maintenance correctement supprimée.", 'success');
                        setTimeout(function () {
                            $('#listing_maintenance').DataTable().ajax.reload(null, false);
                        }, 500);
                    },
                    error: function () {
                        smallBox('Erreur', 'Une erreur est survenu dans la fonction suppressionLigne(paramId).', 'warning');
                    }
                });
            }
            if (ButtonPressed === "Non") {
                smallBox('Suppression', "La maintenance n'à pas été supprimée.", 'warning');
            }
        });
    }

</script>