<?php require_once("inc/init.php"); ?>

<button type="button" class="well" onclick="ouvertureAjout_utilisateur();"><i class="fa fa-plus-square"></i>&nbsp;&nbsp;Nouvel
    utilisateur
</button>

<!-- modal-->
<div class="modal fade" id="modal_ajoute_utilisateur" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
        </div>
    </div>
</div> <!-- fin modal-->


<!-- row -->
<div class="row">

    <!-- NEW WIDGET START -->
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-3" data-widget-editbutton="false"
             data-widget-fullscreenbutton="false">

            <header>
                <span class="widget-icon"> <i class="fa fa-users"></i> </span>
                <h2>Liste des utilisateurs</h2>
            </header>
            <!-- widget div-->
            <div>
                <!-- widget edit box -->
                <div class="jarviswidget-editbox">
                    <!-- This area used as dropdown edit box -->
                </div>
                <!-- end widget edit box -->
                <!-- widget content -->
                <div class="widget-body no-padding">
                    <form id="tableau">
                        <table id="listing_utilisateurs" class="table table-striped table-bordered table-hover"
                               width="100%">
                            <thead>
                            <tr>
                                <th>Utilisateur</th>
                                <th>Local</th>
                                <th>Téléphone mobile</th>
                                <th>Email</th>
                                <th></th>
                            </tr>
                            </thead>
                        </table>
                    </form>

                </div>
                <!-- end widget content -->
            </div>
            <!-- end widget div -->
        </div>
        <!-- end widget -->
    </article>
    <!-- WIDGET END -->
</div>
<!-- end row -->


<script type="text/javascript">
    $(document).ready(function () {


        pageSetUp();

        var pagefunction = function () {

            localStorage.clear();

            var responsiveHelper_listing_utilisateurs = undefined;

            var breakpointDefinition = {
                tablet: 1024,
                phone: 480
            };


            $('#listing_utilisateurs').dataTable({
                "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
                "t" +
                "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
                "oTableTools": {
                    "aButtons": [
                        "xls",
                        {
                            "sExtends": "pdf",
                            "sTitle": "Liste_clients_PDF",
                            "sPdfMessage": "Iwit Systems PDF Export",
                            "sPdfSize": "letter"
                        },
                        {
                            "sExtends": "print",
                            "sMessage": "Generated by Iwit Systems <i>(press Esc to close)</i>"
                        }
                    ],
                    "sSwfPath": "assets/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
                },
                "autoWidth": true,
                "aoColumns": [
                    {sWidth: "300px"},
                    {sWidth: "350px"},
                    {sWidth: "500px"},
                    {sWidth: "500px"},
                    {sWidth: "100px"}
                ],
                "preDrawCallback": function () {
                    if (!responsiveHelper_listing_utilisateurs) {
                        responsiveHelper_listing_utilisateurs = new ResponsiveDatatablesHelper($('#listing_utilisateurs'), breakpointDefinition);
                    }
                },
                "rowCallback": function (nRow) {
                    responsiveHelper_listing_utilisateurs.createExpandIcon(nRow);
                },
                "ajax": "modules/utilisateurs/ajax/iListe_utilisateurs.php",
                "drawCallback": function (oSettings) {
                    responsiveHelper_listing_utilisateurs.respond();
                },
                "language": {
                    "url": "./data/French.json"
                }
            });
        };


        loadScript("assets/js/plugin/datatables/jquery.dataTables.min.js", function () {
            loadScript("assets/js/plugin/datatables/dataTables.colVis.min.js", function () {
                loadScript("assets/js/plugin/datatables/dataTables.tableTools.min.js", function () {
                    loadScript("assets/js/plugin/datatables/dataTables.bootstrap.min.js", function () {
                        loadScript("assets/js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                    });
                });
            });
        });
    });

    function ouvertureAjout_utilisateur() {
        $.ajax({
            url: 'modules/utilisateurs/modals/modal_ajout_utilisateur.php',
            type: 'POST',
            data: '',
            dataType: 'html',
            success: function (contenu) {
                $('#modal_ajoute_utilisateur .modal-content').html(contenu);
                $('#modal_ajoute_utilisateur').modal('show');
            },
            error: function () {
                alert('erreur lors du retour JSON !');
            }
        });
    }

    function ouvertureModification_utilisateur(paramId) {
        window.location = 'index.php?p=modules/modification_utilisateur&id=' + paramId;
    }

    function suppressionLigne(paramId) {
        $.SmartMessageBox({
            title: "Attention !",
            content: "Vous êtes sur le point de supprimer cet utilsateur, confirmer ?",
            buttons: '[Non][Oui]'
        }, function (ButtonPressed) {
            console.log(paramId);
            if (ButtonPressed === "Oui") {
                $.ajax({
                    url: 'modules/utilisateurs/modals/modal_suppression_utilisateur.php',
                    type: 'POST',
                    data: {'id': paramId},
                    dataType: 'html',
                    success: function (contenu) {
                        smallBox('Suppression', "L'utilisateur à correctement été supprimé.", 'success');
                        setTimeout(function () {
                            $('#listing_utilisateurs').DataTable().ajax.reload(null, false);
                        }, 500);
                    },
                    error: function () {
                        smallBox('Erreur', 'Une erreur est survenu dans la fonction suppressionLigne(paramId).', 'warning');
                    }
                });
            }
            if (ButtonPressed === "Non") {
                smallBox('Suppression', "L'équipement n'a pas été supprimé.", 'warning');
            }
        });
    }

</script>