<?php require_once("../inc/init.php"); ?>

<!-- widget grid -->
<section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <!-- Widget ID (each widget will need unique ID)-->
            <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-3" data-widget-editbutton="false"
                 data-widget-fullscreenbutton="false">

                <header>
                    <span class="widget-icon"> <i class="fa fa-users"></i> </span>
                    <h2>Liste des postes affectés</h2>
                </header>
                <!-- widget div-->
                <div>
                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->
                    </div>
                    <!-- end widget edit box -->
                    <!-- widget content -->
                    <div class="widget-body no-padding">
                        <form id="tableau">
                            <table id="datatable_postes_affectes" class="table table-striped table-bordered table-hover"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th>c</th>
                                    <th>ID Affectation</th>
                                    <th>Emplacement</th>
                                    <th>Poste</th>
                                    <th>Utilisateur</th>
                                </tr>
                                </thead>
                            </table>
                        </form>
                    </div>
                    <!-- end widget content -->
                </div>
                <!-- end widget div -->
            </div>
            <!-- end widget -->
        </article>
        <!-- WIDGET END -->

    </div>
    <!-- end row -->

</section>
<!-- end widget grid -->

<script type="text/javascript">

    pageSetUp();

    // pagefunction
    var pagefunction = function () {
        //console.log("cleared");

        /* // DOM Position key index //

         l - Length changing (dropdown)
         f - Filtering input (search)
         t - The Table! (datatable)
         i - Information (records)
         p - Pagination (paging)
         r - pRocessing
         < and > - div elements
         <"#id" and > - div with an id
         <"class" and > - div with a class
         <"#id.class" and > - div with an id and class

         Also see: http://legacy.datatables.net/usage/features
         */

        /* BASIC ;*/
        var responsiveHelper_datatable_postes_affectes = undefined;

        var breakpointDefinition = {
            tablet: 1024,
            phone: 480
        };

        /* TABLETOOLS */
        $('#datatable_postes_affectes').dataTable({

            // Tabletools options:
            // https://datatables.net/extensions/tabletools/button_options
            "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>" +
            "t" +
            "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
            "oTableTools": {
                "aButtons": [
                    "xls",
                    {
                        "sExtends": "pdf",
                        "sTitle": "Liste_clients_PDF",
                        "sPdfMessage": "Iwit Systems PDF Export",
                        "sPdfSize": "letter"
                    },
                    {
                        "sExtends": "print",
                        "sMessage": "Generated by Iwit Systems <i>(press Esc to close)</i>"
                    }
                ],
                "sSwfPath": "assets/js/plugin/datatables/swf/copy_csv_xls_pdf.swf"
            },
            "autoWidth": true,
            "preDrawCallback": function () {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper_datatable_postes_affectes) {
                    responsiveHelper_datatable_postes_affectes = new ResponsiveDatatablesHelper($('#datatable_postes_affectes'), breakpointDefinition);
                }
            },
            "rowCallback": function (nRow) {
                responsiveHelper_datatable_postes_affectes.createExpandIcon(nRow);
            },
            "ajax": "./php/iListe_poste_affectes.php",
            "drawCallback": function (oSettings) {
                responsiveHelper_datatable_postes_affectes.respond();
            },
            "language": {
                "url": "./data/French.json"
            }
        });

        /* END TABLETOOLS */

    };

    // load related plugins

    loadScript("js/plugin/datatables/jquery.dataTables.min.js", function () {
        loadScript("js/plugin/datatables/dataTables.colVis.min.js", function () {
            loadScript("js/plugin/datatables/dataTables.tableTools.min.js", function () {
                loadScript("js/plugin/datatables/dataTables.bootstrap.min.js", function () {
                    loadScript("js/plugin/datatable-responsive/datatables.responsive.min.js", pagefunction)
                });
            });
        });
    });

    /* FONCTION POUR OUVERTURE DES MODAUX POUR MODIFICATIONS */
    function ouvertureModification_poste(paramId) {

        $.ajax({
            url: './php/modal/modal_modification_poste.php',
            type: 'POST',
            data: {'id': paramId},
            dataType: 'html',
            success: function (contenu) {
                $('#modal_affiche_postes_affectes .modal-content').html(contenu);
                $('#modal_affiche_postes_affectes').modal('show');
            },
            error: function () {
                alert('erreur lors du retour JSON !');
            }
        });
    }

    /**
     * Fonction permettant la suppression d'une ligne d'une dataTable par clé primaire
     * @param paramId
     */
    function suppressionLigne(paramId) {
        $.SmartMessageBox({
            title: "Attention !",
            content: "Vous êtes sur le point de supprimer cette ligne, confirmer ?",
            buttons: '[Non][Oui]'
        }, function (ButtonPressed) {
            console.log(paramId);
            if (ButtonPressed === "Oui") {
                $.ajax({
                    url: './php/modal/modal_suppression_local.php',
                    type: 'POST',
                    data: {'id': paramId},
                    dataType: 'html',
                    success: function (contenu) {
                        smallBox('Suppression', "Le logiciel a correctement été supprimé.", 'success');
                    },
                    error: function () {
                        smallBox('Erreur', 'Une erreur est survenu dans la fonction suppressionLigne(paramId).', 'warning');
                    }
                });
            }
            if (ButtonPressed === "Non") {
                smallBox('Suppression', "Le logiciel n'a pas été supprimé.", 'warning');
            }
        });
    }

    function supprimerPlusieursPostes() {
        $.SmartMessageBox({
            title: "Attention !",
            content: "Vous êtes sur le point de supprimer plusieurs postes, confirmer ?",
            buttons: '[Non][Oui]'
        }, function (ButtonPressed) {
            if (ButtonPressed === "Oui") {
                $.ajax({
                    url: './php/modal/modal_suppression_postes.php',
                    type: 'POST',
                    data: $('#tableau').serialize(),
                    dataType: 'json',
                    success: function (data) {
                        if (data.retour == '0') {
                            smallBox('Suppression', "Les logiciels ont correctement été supprimés.", 'success');
                        } else {
                            smallBox('Suppression', "Les logicels n'ont pas pu être supprimés.", 'warning');
                        }
                    },
                    error: function () {
                        smallBox('Erreur', 'Un problème est survenu durant la suppression.', 'warning');
                    }
                });
            }
            if (ButtonPressed === "Non") {
                smallBox('Suppression', "Suppression annulée.", 'warning');
            }
        });
    }

</script>
